# Generated by Django 5.2.6 on 2025-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('No_of_tickets', models.IntegerField()),
            ],
        ),
    ]
