# Generated by Django 5.2.6 on 2025-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='No_of_tickets',
            field=models.IntegerField(null=True),
        ),
    ]
