# Generated by Django 5.2.6 on 2025-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_customer_no_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unpaid',
            field=models.IntegerField(default=0),
        ),
    ]
