# Generated by Django 5.2.6 on 2025-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customer_unpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
