# Generated by Django 5.2.6 on 2025-09-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_customer_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='unpaid',
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.CharField(default='not paid'),
        ),
    ]
