# Generated by Django 5.2.6 on 2025-09-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_customer_unpaid_customer_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receipt',
            field=models.IntegerField(default=500),
        ),
    ]
