# Generated by Django 5.2.6 on 2025-09-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_customer_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='receipt',
            field=models.IntegerField(null=True),
        ),
    ]
